// message/message.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.31.1
// source: message/message.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AllocateRoomIdStatus int32

const (
	AllocateRoomIdStatus_ALLOCATE_ROOM_ID_SUCCESS             AllocateRoomIdStatus = 0
	AllocateRoomIdStatus_ALLOCATE_ROOM_ID_FAILED              AllocateRoomIdStatus = 1
	AllocateRoomIdStatus_ALLOCATE_ROOM_ID_SERVICE_UNAVAILABLE AllocateRoomIdStatus = 2
)

// Enum value maps for AllocateRoomIdStatus.
var (
	AllocateRoomIdStatus_name = map[int32]string{
		0: "ALLOCATE_ROOM_ID_SUCCESS",
		1: "ALLOCATE_ROOM_ID_FAILED",
		2: "ALLOCATE_ROOM_ID_SERVICE_UNAVAILABLE",
	}
	AllocateRoomIdStatus_value = map[string]int32{
		"ALLOCATE_ROOM_ID_SUCCESS":             0,
		"ALLOCATE_ROOM_ID_FAILED":              1,
		"ALLOCATE_ROOM_ID_SERVICE_UNAVAILABLE": 2,
	}
)

func (x AllocateRoomIdStatus) Enum() *AllocateRoomIdStatus {
	p := new(AllocateRoomIdStatus)
	*p = x
	return p
}

func (x AllocateRoomIdStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AllocateRoomIdStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_message_message_proto_enumTypes[0].Descriptor()
}

func (AllocateRoomIdStatus) Type() protoreflect.EnumType {
	return &file_message_message_proto_enumTypes[0]
}

func (x AllocateRoomIdStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AllocateRoomIdStatus.Descriptor instead.
func (AllocateRoomIdStatus) EnumDescriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{0}
}

type CreateRoomStatus int32

const (
	CreateRoomStatus_CREATE_ROOM_SUCCESS        CreateRoomStatus = 0
	CreateRoomStatus_CREATE_ROOM_FAILED         CreateRoomStatus = 1
	CreateRoomStatus_CREATE_ROOM_ROOM_EXISTS    CreateRoomStatus = 2
	CreateRoomStatus_CREATE_ROOM_INVALID_PARAMS CreateRoomStatus = 3
)

// Enum value maps for CreateRoomStatus.
var (
	CreateRoomStatus_name = map[int32]string{
		0: "CREATE_ROOM_SUCCESS",
		1: "CREATE_ROOM_FAILED",
		2: "CREATE_ROOM_ROOM_EXISTS",
		3: "CREATE_ROOM_INVALID_PARAMS",
	}
	CreateRoomStatus_value = map[string]int32{
		"CREATE_ROOM_SUCCESS":        0,
		"CREATE_ROOM_FAILED":         1,
		"CREATE_ROOM_ROOM_EXISTS":    2,
		"CREATE_ROOM_INVALID_PARAMS": 3,
	}
)

func (x CreateRoomStatus) Enum() *CreateRoomStatus {
	p := new(CreateRoomStatus)
	*p = x
	return p
}

func (x CreateRoomStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreateRoomStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_message_message_proto_enumTypes[1].Descriptor()
}

func (CreateRoomStatus) Type() protoreflect.EnumType {
	return &file_message_message_proto_enumTypes[1]
}

func (x CreateRoomStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreateRoomStatus.Descriptor instead.
func (CreateRoomStatus) EnumDescriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{1}
}

type JoinRoomStatus int32

const (
	JoinRoomStatus_JOIN_ROOM_SUCCESS         JoinRoomStatus = 0
	JoinRoomStatus_JOIN_ROOM_FAILED          JoinRoomStatus = 1
	JoinRoomStatus_JOIN_ROOM_ROOM_NOT_FOUND  JoinRoomStatus = 2
	JoinRoomStatus_JOIN_ROOM_ROOM_FULL       JoinRoomStatus = 3
	JoinRoomStatus_JOIN_ROOM_WRONG_PASSWORD  JoinRoomStatus = 4
	JoinRoomStatus_JOIN_ROOM_ALREADY_IN_ROOM JoinRoomStatus = 5
)

// Enum value maps for JoinRoomStatus.
var (
	JoinRoomStatus_name = map[int32]string{
		0: "JOIN_ROOM_SUCCESS",
		1: "JOIN_ROOM_FAILED",
		2: "JOIN_ROOM_ROOM_NOT_FOUND",
		3: "JOIN_ROOM_ROOM_FULL",
		4: "JOIN_ROOM_WRONG_PASSWORD",
		5: "JOIN_ROOM_ALREADY_IN_ROOM",
	}
	JoinRoomStatus_value = map[string]int32{
		"JOIN_ROOM_SUCCESS":         0,
		"JOIN_ROOM_FAILED":          1,
		"JOIN_ROOM_ROOM_NOT_FOUND":  2,
		"JOIN_ROOM_ROOM_FULL":       3,
		"JOIN_ROOM_WRONG_PASSWORD":  4,
		"JOIN_ROOM_ALREADY_IN_ROOM": 5,
	}
)

func (x JoinRoomStatus) Enum() *JoinRoomStatus {
	p := new(JoinRoomStatus)
	*p = x
	return p
}

func (x JoinRoomStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JoinRoomStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_message_message_proto_enumTypes[2].Descriptor()
}

func (JoinRoomStatus) Type() protoreflect.EnumType {
	return &file_message_message_proto_enumTypes[2]
}

func (x JoinRoomStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JoinRoomStatus.Descriptor instead.
func (JoinRoomStatus) EnumDescriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{2}
}

type LeaveRoomStatus int32

const (
	LeaveRoomStatus_LEAVE_ROOM_SUCCESS     LeaveRoomStatus = 0
	LeaveRoomStatus_LEAVE_ROOM_FAILED      LeaveRoomStatus = 1
	LeaveRoomStatus_LEAVE_ROOM_NOT_IN_ROOM LeaveRoomStatus = 2
)

// Enum value maps for LeaveRoomStatus.
var (
	LeaveRoomStatus_name = map[int32]string{
		0: "LEAVE_ROOM_SUCCESS",
		1: "LEAVE_ROOM_FAILED",
		2: "LEAVE_ROOM_NOT_IN_ROOM",
	}
	LeaveRoomStatus_value = map[string]int32{
		"LEAVE_ROOM_SUCCESS":     0,
		"LEAVE_ROOM_FAILED":      1,
		"LEAVE_ROOM_NOT_IN_ROOM": 2,
	}
)

func (x LeaveRoomStatus) Enum() *LeaveRoomStatus {
	p := new(LeaveRoomStatus)
	*p = x
	return p
}

func (x LeaveRoomStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LeaveRoomStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_message_message_proto_enumTypes[3].Descriptor()
}

func (LeaveRoomStatus) Type() protoreflect.EnumType {
	return &file_message_message_proto_enumTypes[3]
}

func (x LeaveRoomStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LeaveRoomStatus.Descriptor instead.
func (LeaveRoomStatus) EnumDescriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{3}
}

type CloseRoomStatus int32

const (
	CloseRoomStatus_CLOSE_ROOM_SUCCESS        CloseRoomStatus = 0
	CloseRoomStatus_CLOSE_ROOM_FAILED         CloseRoomStatus = 1
	CloseRoomStatus_CLOSE_ROOM_NOT_OWNER      CloseRoomStatus = 2
	CloseRoomStatus_CLOSE_ROOM_ROOM_NOT_FOUND CloseRoomStatus = 3
)

// Enum value maps for CloseRoomStatus.
var (
	CloseRoomStatus_name = map[int32]string{
		0: "CLOSE_ROOM_SUCCESS",
		1: "CLOSE_ROOM_FAILED",
		2: "CLOSE_ROOM_NOT_OWNER",
		3: "CLOSE_ROOM_ROOM_NOT_FOUND",
	}
	CloseRoomStatus_value = map[string]int32{
		"CLOSE_ROOM_SUCCESS":        0,
		"CLOSE_ROOM_FAILED":         1,
		"CLOSE_ROOM_NOT_OWNER":      2,
		"CLOSE_ROOM_ROOM_NOT_FOUND": 3,
	}
)

func (x CloseRoomStatus) Enum() *CloseRoomStatus {
	p := new(CloseRoomStatus)
	*p = x
	return p
}

func (x CloseRoomStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CloseRoomStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_message_message_proto_enumTypes[4].Descriptor()
}

func (CloseRoomStatus) Type() protoreflect.EnumType {
	return &file_message_message_proto_enumTypes[4]
}

func (x CloseRoomStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CloseRoomStatus.Descriptor instead.
func (CloseRoomStatus) EnumDescriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{4}
}

type ChatMessageStatus int32

const (
	ChatMessageStatus_CHAT_MESSAGE_SUCCESS          ChatMessageStatus = 0
	ChatMessageStatus_CHAT_MESSAGE_FAILED           ChatMessageStatus = 1
	ChatMessageStatus_CHAT_MESSAGE_USER_NOT_IN_ROOM ChatMessageStatus = 2
	ChatMessageStatus_CHAT_MESSAGE_ROOM_NOT_FOUND   ChatMessageStatus = 3
	ChatMessageStatus_CHAT_MESSAGE_ROOM_CLOSED      ChatMessageStatus = 4
	ChatMessageStatus_CHAT_MESSAGE_CONTENT_TOO_LONG ChatMessageStatus = 5
)

// Enum value maps for ChatMessageStatus.
var (
	ChatMessageStatus_name = map[int32]string{
		0: "CHAT_MESSAGE_SUCCESS",
		1: "CHAT_MESSAGE_FAILED",
		2: "CHAT_MESSAGE_USER_NOT_IN_ROOM",
		3: "CHAT_MESSAGE_ROOM_NOT_FOUND",
		4: "CHAT_MESSAGE_ROOM_CLOSED",
		5: "CHAT_MESSAGE_CONTENT_TOO_LONG",
	}
	ChatMessageStatus_value = map[string]int32{
		"CHAT_MESSAGE_SUCCESS":          0,
		"CHAT_MESSAGE_FAILED":           1,
		"CHAT_MESSAGE_USER_NOT_IN_ROOM": 2,
		"CHAT_MESSAGE_ROOM_NOT_FOUND":   3,
		"CHAT_MESSAGE_ROOM_CLOSED":      4,
		"CHAT_MESSAGE_CONTENT_TOO_LONG": 5,
	}
)

func (x ChatMessageStatus) Enum() *ChatMessageStatus {
	p := new(ChatMessageStatus)
	*p = x
	return p
}

func (x ChatMessageStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChatMessageStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_message_message_proto_enumTypes[5].Descriptor()
}

func (ChatMessageStatus) Type() protoreflect.EnumType {
	return &file_message_message_proto_enumTypes[5]
}

func (x ChatMessageStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChatMessageStatus.Descriptor instead.
func (ChatMessageStatus) EnumDescriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{5}
}

type MessageType int32

const (
	MessageType_MESSAGE_TYPE_TEXT  MessageType = 0
	MessageType_MESSAGE_TYPE_IMAGE MessageType = 1
	MessageType_MESSAGE_TYPE_FILE  MessageType = 2
	MessageType_MESSAGE_TYPE_VOICE MessageType = 3
	MessageType_MESSAGE_TYPE_VIDEO MessageType = 4
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "MESSAGE_TYPE_TEXT",
		1: "MESSAGE_TYPE_IMAGE",
		2: "MESSAGE_TYPE_FILE",
		3: "MESSAGE_TYPE_VOICE",
		4: "MESSAGE_TYPE_VIDEO",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_TYPE_TEXT":  0,
		"MESSAGE_TYPE_IMAGE": 1,
		"MESSAGE_TYPE_FILE":  2,
		"MESSAGE_TYPE_VOICE": 3,
		"MESSAGE_TYPE_VIDEO": 4,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_message_message_proto_enumTypes[6].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_message_message_proto_enumTypes[6]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{6}
}

type RoomMessageFetchStatus int32

const (
	RoomMessageFetchStatus_ROOM_MESSAGE_FETCH_SUCCESS        RoomMessageFetchStatus = 0
	RoomMessageFetchStatus_ROOM_MESSAGE_FETCH_FAILED         RoomMessageFetchStatus = 1
	RoomMessageFetchStatus_ROOM_MESSAGE_FETCH_ROOM_NOT_FOUND RoomMessageFetchStatus = 2
	RoomMessageFetchStatus_ROOM_MESSAGE_FETCH_ACCESS_DENIED  RoomMessageFetchStatus = 3
)

// Enum value maps for RoomMessageFetchStatus.
var (
	RoomMessageFetchStatus_name = map[int32]string{
		0: "ROOM_MESSAGE_FETCH_SUCCESS",
		1: "ROOM_MESSAGE_FETCH_FAILED",
		2: "ROOM_MESSAGE_FETCH_ROOM_NOT_FOUND",
		3: "ROOM_MESSAGE_FETCH_ACCESS_DENIED",
	}
	RoomMessageFetchStatus_value = map[string]int32{
		"ROOM_MESSAGE_FETCH_SUCCESS":        0,
		"ROOM_MESSAGE_FETCH_FAILED":         1,
		"ROOM_MESSAGE_FETCH_ROOM_NOT_FOUND": 2,
		"ROOM_MESSAGE_FETCH_ACCESS_DENIED":  3,
	}
)

func (x RoomMessageFetchStatus) Enum() *RoomMessageFetchStatus {
	p := new(RoomMessageFetchStatus)
	*p = x
	return p
}

func (x RoomMessageFetchStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomMessageFetchStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_message_message_proto_enumTypes[7].Descriptor()
}

func (RoomMessageFetchStatus) Type() protoreflect.EnumType {
	return &file_message_message_proto_enumTypes[7]
}

func (x RoomMessageFetchStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoomMessageFetchStatus.Descriptor instead.
func (RoomMessageFetchStatus) EnumDescriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{7}
}

type MessageStatus int32

const (
	MessageStatus_MESSAGE_STATUS_UNKNOWN    MessageStatus = 0
	MessageStatus_MESSAGE_STATUS_PENDING    MessageStatus = 1 // 待处理
	MessageStatus_MESSAGE_STATUS_PROCESSING MessageStatus = 2 // 处理中
	MessageStatus_MESSAGE_STATUS_SUCCESS    MessageStatus = 3 // 成功
	MessageStatus_MESSAGE_STATUS_FAILED     MessageStatus = 4 // 失败
	MessageStatus_MESSAGE_STATUS_TIMEOUT    MessageStatus = 5 // 超时
)

// Enum value maps for MessageStatus.
var (
	MessageStatus_name = map[int32]string{
		0: "MESSAGE_STATUS_UNKNOWN",
		1: "MESSAGE_STATUS_PENDING",
		2: "MESSAGE_STATUS_PROCESSING",
		3: "MESSAGE_STATUS_SUCCESS",
		4: "MESSAGE_STATUS_FAILED",
		5: "MESSAGE_STATUS_TIMEOUT",
	}
	MessageStatus_value = map[string]int32{
		"MESSAGE_STATUS_UNKNOWN":    0,
		"MESSAGE_STATUS_PENDING":    1,
		"MESSAGE_STATUS_PROCESSING": 2,
		"MESSAGE_STATUS_SUCCESS":    3,
		"MESSAGE_STATUS_FAILED":     4,
		"MESSAGE_STATUS_TIMEOUT":    5,
	}
)

func (x MessageStatus) Enum() *MessageStatus {
	p := new(MessageStatus)
	*p = x
	return p
}

func (x MessageStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_message_message_proto_enumTypes[8].Descriptor()
}

func (MessageStatus) Type() protoreflect.EnumType {
	return &file_message_message_proto_enumTypes[8]
}

func (x MessageStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageStatus.Descriptor instead.
func (MessageStatus) EnumDescriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{8}
}

type RoomStatus int32

const (
	RoomStatus_ROOM_STATUS_OPEN   RoomStatus = 0
	RoomStatus_ROOM_STATUS_CLOSED RoomStatus = 1
	RoomStatus_ROOM_STATUS_FULL   RoomStatus = 2
)

// Enum value maps for RoomStatus.
var (
	RoomStatus_name = map[int32]string{
		0: "ROOM_STATUS_OPEN",
		1: "ROOM_STATUS_CLOSED",
		2: "ROOM_STATUS_FULL",
	}
	RoomStatus_value = map[string]int32{
		"ROOM_STATUS_OPEN":   0,
		"ROOM_STATUS_CLOSED": 1,
		"ROOM_STATUS_FULL":   2,
	}
)

func (x RoomStatus) Enum() *RoomStatus {
	p := new(RoomStatus)
	*p = x
	return p
}

func (x RoomStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_message_message_proto_enumTypes[9].Descriptor()
}

func (RoomStatus) Type() protoreflect.EnumType {
	return &file_message_message_proto_enumTypes[9]
}

func (x RoomStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoomStatus.Descriptor instead.
func (RoomStatus) EnumDescriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{9}
}

// 消息信封 - 所有消息的公共字段
type MessageEnvelope struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ConnectionSeqId uint64                 `protobuf:"varint,1,opt,name=connection_seq_id,json=connectionSeqId,proto3" json:"connection_seq_id,omitempty"` // 连接序列号
	MessageId       []byte                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`                      // 128位全局消息ID (16字节，时间戳[48bit]+用户ID[32bit]+房间号[32bit]+登录ID[4bit,支持多端登录]+序号[6bit]+自定义[6bit])
	// Types that are valid to be assigned to Message:
	//
	//	*MessageEnvelope_AllocateRoomId
	//	*MessageEnvelope_AllocateRoomIdAck
	//	*MessageEnvelope_CreateRoom
	//	*MessageEnvelope_CreateRoomAck
	//	*MessageEnvelope_JoinRoom
	//	*MessageEnvelope_JoinRoomAck
	//	*MessageEnvelope_LeaveRoom
	//	*MessageEnvelope_LeaveRoomAck
	//	*MessageEnvelope_CloseRoom
	//	*MessageEnvelope_CloseRoomAck
	//	*MessageEnvelope_ChatMessage
	//	*MessageEnvelope_ChatMessageAck
	//	*MessageEnvelope_MessageFetchRequest
	//	*MessageEnvelope_MessageFetchResponse
	//	*MessageEnvelope_RoomMessageFetchRequest
	//	*MessageEnvelope_RoomMessageFetchResponse
	//	*MessageEnvelope_Heartbeat
	//	*MessageEnvelope_HeartbeatAck
	Message       isMessageEnvelope_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageEnvelope) Reset() {
	*x = MessageEnvelope{}
	mi := &file_message_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageEnvelope) ProtoMessage() {}

func (x *MessageEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageEnvelope.ProtoReflect.Descriptor instead.
func (*MessageEnvelope) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{0}
}

func (x *MessageEnvelope) GetConnectionSeqId() uint64 {
	if x != nil {
		return x.ConnectionSeqId
	}
	return 0
}

func (x *MessageEnvelope) GetMessageId() []byte {
	if x != nil {
		return x.MessageId
	}
	return nil
}

func (x *MessageEnvelope) GetMessage() isMessageEnvelope_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *MessageEnvelope) GetAllocateRoomId() *AllocateRoomId {
	if x != nil {
		if x, ok := x.Message.(*MessageEnvelope_AllocateRoomId); ok {
			return x.AllocateRoomId
		}
	}
	return nil
}

func (x *MessageEnvelope) GetAllocateRoomIdAck() *AllocateRoomIdAck {
	if x != nil {
		if x, ok := x.Message.(*MessageEnvelope_AllocateRoomIdAck); ok {
			return x.AllocateRoomIdAck
		}
	}
	return nil
}

func (x *MessageEnvelope) GetCreateRoom() *CreateRoom {
	if x != nil {
		if x, ok := x.Message.(*MessageEnvelope_CreateRoom); ok {
			return x.CreateRoom
		}
	}
	return nil
}

func (x *MessageEnvelope) GetCreateRoomAck() *CreateRoomAck {
	if x != nil {
		if x, ok := x.Message.(*MessageEnvelope_CreateRoomAck); ok {
			return x.CreateRoomAck
		}
	}
	return nil
}

func (x *MessageEnvelope) GetJoinRoom() *JoinRoom {
	if x != nil {
		if x, ok := x.Message.(*MessageEnvelope_JoinRoom); ok {
			return x.JoinRoom
		}
	}
	return nil
}

func (x *MessageEnvelope) GetJoinRoomAck() *JoinRoomAck {
	if x != nil {
		if x, ok := x.Message.(*MessageEnvelope_JoinRoomAck); ok {
			return x.JoinRoomAck
		}
	}
	return nil
}

func (x *MessageEnvelope) GetLeaveRoom() *LeaveRoom {
	if x != nil {
		if x, ok := x.Message.(*MessageEnvelope_LeaveRoom); ok {
			return x.LeaveRoom
		}
	}
	return nil
}

func (x *MessageEnvelope) GetLeaveRoomAck() *LeaveRoomAck {
	if x != nil {
		if x, ok := x.Message.(*MessageEnvelope_LeaveRoomAck); ok {
			return x.LeaveRoomAck
		}
	}
	return nil
}

func (x *MessageEnvelope) GetCloseRoom() *CloseRoom {
	if x != nil {
		if x, ok := x.Message.(*MessageEnvelope_CloseRoom); ok {
			return x.CloseRoom
		}
	}
	return nil
}

func (x *MessageEnvelope) GetCloseRoomAck() *CloseRoomAck {
	if x != nil {
		if x, ok := x.Message.(*MessageEnvelope_CloseRoomAck); ok {
			return x.CloseRoomAck
		}
	}
	return nil
}

func (x *MessageEnvelope) GetChatMessage() *ChatMessage {
	if x != nil {
		if x, ok := x.Message.(*MessageEnvelope_ChatMessage); ok {
			return x.ChatMessage
		}
	}
	return nil
}

func (x *MessageEnvelope) GetChatMessageAck() *ChatMessageAck {
	if x != nil {
		if x, ok := x.Message.(*MessageEnvelope_ChatMessageAck); ok {
			return x.ChatMessageAck
		}
	}
	return nil
}

func (x *MessageEnvelope) GetMessageFetchRequest() *MessageFetchRequest {
	if x != nil {
		if x, ok := x.Message.(*MessageEnvelope_MessageFetchRequest); ok {
			return x.MessageFetchRequest
		}
	}
	return nil
}

func (x *MessageEnvelope) GetMessageFetchResponse() *MessageFetchResponse {
	if x != nil {
		if x, ok := x.Message.(*MessageEnvelope_MessageFetchResponse); ok {
			return x.MessageFetchResponse
		}
	}
	return nil
}

func (x *MessageEnvelope) GetRoomMessageFetchRequest() *RoomMessageFetchRequest {
	if x != nil {
		if x, ok := x.Message.(*MessageEnvelope_RoomMessageFetchRequest); ok {
			return x.RoomMessageFetchRequest
		}
	}
	return nil
}

func (x *MessageEnvelope) GetRoomMessageFetchResponse() *RoomMessageFetchResponse {
	if x != nil {
		if x, ok := x.Message.(*MessageEnvelope_RoomMessageFetchResponse); ok {
			return x.RoomMessageFetchResponse
		}
	}
	return nil
}

func (x *MessageEnvelope) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Message.(*MessageEnvelope_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *MessageEnvelope) GetHeartbeatAck() *HeartbeatAck {
	if x != nil {
		if x, ok := x.Message.(*MessageEnvelope_HeartbeatAck); ok {
			return x.HeartbeatAck
		}
	}
	return nil
}

type isMessageEnvelope_Message interface {
	isMessageEnvelope_Message()
}

type MessageEnvelope_AllocateRoomId struct {
	// 房间管理
	AllocateRoomId *AllocateRoomId `protobuf:"bytes,10,opt,name=allocate_room_id,json=allocateRoomId,proto3,oneof"` // 客户端请求分配房间号
}

type MessageEnvelope_AllocateRoomIdAck struct {
	AllocateRoomIdAck *AllocateRoomIdAck `protobuf:"bytes,11,opt,name=allocate_room_id_ack,json=allocateRoomIdAck,proto3,oneof"` // 分配房间号确认
}

type MessageEnvelope_CreateRoom struct {
	CreateRoom *CreateRoom `protobuf:"bytes,12,opt,name=create_room,json=createRoom,proto3,oneof"` // 创建房间（配置房间参数）
}

type MessageEnvelope_CreateRoomAck struct {
	CreateRoomAck *CreateRoomAck `protobuf:"bytes,13,opt,name=create_room_ack,json=createRoomAck,proto3,oneof"` // 创建房间确认
}

type MessageEnvelope_JoinRoom struct {
	JoinRoom *JoinRoom `protobuf:"bytes,14,opt,name=join_room,json=joinRoom,proto3,oneof"` // 加入房间
}

type MessageEnvelope_JoinRoomAck struct {
	JoinRoomAck *JoinRoomAck `protobuf:"bytes,15,opt,name=join_room_ack,json=joinRoomAck,proto3,oneof"` // 加入房间确认
}

type MessageEnvelope_LeaveRoom struct {
	LeaveRoom *LeaveRoom `protobuf:"bytes,16,opt,name=leave_room,json=leaveRoom,proto3,oneof"` // 离开房间
}

type MessageEnvelope_LeaveRoomAck struct {
	LeaveRoomAck *LeaveRoomAck `protobuf:"bytes,17,opt,name=leave_room_ack,json=leaveRoomAck,proto3,oneof"` // 离开房间确认
}

type MessageEnvelope_CloseRoom struct {
	CloseRoom *CloseRoom `protobuf:"bytes,18,opt,name=close_room,json=closeRoom,proto3,oneof"` // 关闭房间
}

type MessageEnvelope_CloseRoomAck struct {
	CloseRoomAck *CloseRoomAck `protobuf:"bytes,19,opt,name=close_room_ack,json=closeRoomAck,proto3,oneof"` // 关闭房间确认
}

type MessageEnvelope_ChatMessage struct {
	// 聊天消息
	ChatMessage *ChatMessage `protobuf:"bytes,20,opt,name=chat_message,json=chatMessage,proto3,oneof"`
}

type MessageEnvelope_ChatMessageAck struct {
	ChatMessageAck *ChatMessageAck `protobuf:"bytes,21,opt,name=chat_message_ack,json=chatMessageAck,proto3,oneof"`
}

type MessageEnvelope_MessageFetchRequest struct {
	// 消息查询
	MessageFetchRequest *MessageFetchRequest `protobuf:"bytes,40,opt,name=message_fetch_request,json=messageFetchRequest,proto3,oneof"` // 查询特定消息（情况1和3）
}

type MessageEnvelope_MessageFetchResponse struct {
	MessageFetchResponse *MessageFetchResponse `protobuf:"bytes,41,opt,name=message_fetch_response,json=messageFetchResponse,proto3,oneof"` // 查询特定消息响应
}

type MessageEnvelope_RoomMessageFetchRequest struct {
	RoomMessageFetchRequest *RoomMessageFetchRequest `protobuf:"bytes,42,opt,name=room_message_fetch_request,json=roomMessageFetchRequest,proto3,oneof"` // 拉取房间消息（情况2）
}

type MessageEnvelope_RoomMessageFetchResponse struct {
	RoomMessageFetchResponse *RoomMessageFetchResponse `protobuf:"bytes,43,opt,name=room_message_fetch_response,json=roomMessageFetchResponse,proto3,oneof"` // 拉取房间消息响应
}

type MessageEnvelope_Heartbeat struct {
	// 心跳
	Heartbeat *Heartbeat `protobuf:"bytes,50,opt,name=heartbeat,proto3,oneof"`
}

type MessageEnvelope_HeartbeatAck struct {
	HeartbeatAck *HeartbeatAck `protobuf:"bytes,51,opt,name=heartbeat_ack,json=heartbeatAck,proto3,oneof"`
}

func (*MessageEnvelope_AllocateRoomId) isMessageEnvelope_Message() {}

func (*MessageEnvelope_AllocateRoomIdAck) isMessageEnvelope_Message() {}

func (*MessageEnvelope_CreateRoom) isMessageEnvelope_Message() {}

func (*MessageEnvelope_CreateRoomAck) isMessageEnvelope_Message() {}

func (*MessageEnvelope_JoinRoom) isMessageEnvelope_Message() {}

func (*MessageEnvelope_JoinRoomAck) isMessageEnvelope_Message() {}

func (*MessageEnvelope_LeaveRoom) isMessageEnvelope_Message() {}

func (*MessageEnvelope_LeaveRoomAck) isMessageEnvelope_Message() {}

func (*MessageEnvelope_CloseRoom) isMessageEnvelope_Message() {}

func (*MessageEnvelope_CloseRoomAck) isMessageEnvelope_Message() {}

func (*MessageEnvelope_ChatMessage) isMessageEnvelope_Message() {}

func (*MessageEnvelope_ChatMessageAck) isMessageEnvelope_Message() {}

func (*MessageEnvelope_MessageFetchRequest) isMessageEnvelope_Message() {}

func (*MessageEnvelope_MessageFetchResponse) isMessageEnvelope_Message() {}

func (*MessageEnvelope_RoomMessageFetchRequest) isMessageEnvelope_Message() {}

func (*MessageEnvelope_RoomMessageFetchResponse) isMessageEnvelope_Message() {}

func (*MessageEnvelope_Heartbeat) isMessageEnvelope_Message() {}

func (*MessageEnvelope_HeartbeatAck) isMessageEnvelope_Message() {}

// 客户端请求分配房间号
type AllocateRoomId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateRoomId) Reset() {
	*x = AllocateRoomId{}
	mi := &file_message_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateRoomId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateRoomId) ProtoMessage() {}

func (x *AllocateRoomId) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateRoomId.ProtoReflect.Descriptor instead.
func (*AllocateRoomId) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{1}
}

// 分配房间号确认
type AllocateRoomIdAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        uint64                 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`                     // 分配的房间ID
	Status        AllocateRoomIdStatus   `protobuf:"varint,2,opt,name=status,proto3,enum=message.AllocateRoomIdStatus" json:"status,omitempty"` // 状态
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`                                    // 失败原因
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateRoomIdAck) Reset() {
	*x = AllocateRoomIdAck{}
	mi := &file_message_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateRoomIdAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateRoomIdAck) ProtoMessage() {}

func (x *AllocateRoomIdAck) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateRoomIdAck.ProtoReflect.Descriptor instead.
func (*AllocateRoomIdAck) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{2}
}

func (x *AllocateRoomIdAck) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *AllocateRoomIdAck) GetStatus() AllocateRoomIdStatus {
	if x != nil {
		return x.Status
	}
	return AllocateRoomIdStatus_ALLOCATE_ROOM_ID_SUCCESS
}

func (x *AllocateRoomIdAck) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// 创建房间（配置房间参数）
type CreateRoom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        uint64                 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`             // 房间ID (使用分配到的房间号)
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                // 房间名称
	MaxMembers    uint32                 `protobuf:"varint,3,opt,name=max_members,json=maxMembers,proto3" json:"max_members,omitempty"` // 最大成员数
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`                        // 房间密码 (可选)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoom) Reset() {
	*x = CreateRoom{}
	mi := &file_message_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoom) ProtoMessage() {}

func (x *CreateRoom) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoom.ProtoReflect.Descriptor instead.
func (*CreateRoom) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRoom) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *CreateRoom) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRoom) GetMaxMembers() uint32 {
	if x != nil {
		return x.MaxMembers
	}
	return 0
}

func (x *CreateRoom) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// 创建房间确认
type CreateRoomAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        uint64                 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`                 // 房间ID
	Status        CreateRoomStatus       `protobuf:"varint,2,opt,name=status,proto3,enum=message.CreateRoomStatus" json:"status,omitempty"` // 状态
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`                                // 失败原因
	RouterAddrs   []string               `protobuf:"bytes,4,rep,name=router_addrs,json=routerAddrs,proto3" json:"router_addrs,omitempty"`   // 关联的路由节点地址列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomAck) Reset() {
	*x = CreateRoomAck{}
	mi := &file_message_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomAck) ProtoMessage() {}

func (x *CreateRoomAck) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomAck.ProtoReflect.Descriptor instead.
func (*CreateRoomAck) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{4}
}

func (x *CreateRoomAck) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *CreateRoomAck) GetStatus() CreateRoomStatus {
	if x != nil {
		return x.Status
	}
	return CreateRoomStatus_CREATE_ROOM_SUCCESS
}

func (x *CreateRoomAck) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CreateRoomAck) GetRouterAddrs() []string {
	if x != nil {
		return x.RouterAddrs
	}
	return nil
}

// 加入房间
type JoinRoom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      string                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"` // 房间密码 (如果房间设置了密码)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoom) Reset() {
	*x = JoinRoom{}
	mi := &file_message_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoom) ProtoMessage() {}

func (x *JoinRoom) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoom.ProtoReflect.Descriptor instead.
func (*JoinRoom) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{5}
}

func (x *JoinRoom) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// 加入房间确认
type JoinRoomAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        uint64                 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`               // 房间ID
	Status        JoinRoomStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=message.JoinRoomStatus" json:"status,omitempty"` // 状态
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`                              // 失败原因
	RoomInfo      *RoomInfo              `protobuf:"bytes,4,opt,name=room_info,json=roomInfo,proto3" json:"room_info,omitempty"`          // 房间信息
	RouterAddrs   []string               `protobuf:"bytes,5,rep,name=router_addrs,json=routerAddrs,proto3" json:"router_addrs,omitempty"` // 关联的路由节点地址列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomAck) Reset() {
	*x = JoinRoomAck{}
	mi := &file_message_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomAck) ProtoMessage() {}

func (x *JoinRoomAck) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomAck.ProtoReflect.Descriptor instead.
func (*JoinRoomAck) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{6}
}

func (x *JoinRoomAck) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *JoinRoomAck) GetStatus() JoinRoomStatus {
	if x != nil {
		return x.Status
	}
	return JoinRoomStatus_JOIN_ROOM_SUCCESS
}

func (x *JoinRoomAck) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *JoinRoomAck) GetRoomInfo() *RoomInfo {
	if x != nil {
		return x.RoomInfo
	}
	return nil
}

func (x *JoinRoomAck) GetRouterAddrs() []string {
	if x != nil {
		return x.RouterAddrs
	}
	return nil
}

// 离开房间
type LeaveRoom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRoom) Reset() {
	*x = LeaveRoom{}
	mi := &file_message_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoom) ProtoMessage() {}

func (x *LeaveRoom) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoom.ProtoReflect.Descriptor instead.
func (*LeaveRoom) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{7}
}

// 离开房间确认
type LeaveRoomAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        uint64                 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`                // 房间ID
	Status        LeaveRoomStatus        `protobuf:"varint,2,opt,name=status,proto3,enum=message.LeaveRoomStatus" json:"status,omitempty"` // 状态
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`                               // 失败原因
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRoomAck) Reset() {
	*x = LeaveRoomAck{}
	mi := &file_message_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRoomAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoomAck) ProtoMessage() {}

func (x *LeaveRoomAck) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoomAck.ProtoReflect.Descriptor instead.
func (*LeaveRoomAck) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{8}
}

func (x *LeaveRoomAck) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *LeaveRoomAck) GetStatus() LeaveRoomStatus {
	if x != nil {
		return x.Status
	}
	return LeaveRoomStatus_LEAVE_ROOM_SUCCESS
}

func (x *LeaveRoomAck) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// 关闭房间
type CloseRoom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseRoom) Reset() {
	*x = CloseRoom{}
	mi := &file_message_message_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseRoom) ProtoMessage() {}

func (x *CloseRoom) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseRoom.ProtoReflect.Descriptor instead.
func (*CloseRoom) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{9}
}

// 关闭房间确认
type CloseRoomAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        uint64                 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`                // 房间ID
	Status        CloseRoomStatus        `protobuf:"varint,2,opt,name=status,proto3,enum=message.CloseRoomStatus" json:"status,omitempty"` // 状态
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`                               // 失败原因
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseRoomAck) Reset() {
	*x = CloseRoomAck{}
	mi := &file_message_message_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseRoomAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseRoomAck) ProtoMessage() {}

func (x *CloseRoomAck) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseRoomAck.ProtoReflect.Descriptor instead.
func (*CloseRoomAck) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{10}
}

func (x *CloseRoomAck) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *CloseRoomAck) GetStatus() CloseRoomStatus {
	if x != nil {
		return x.Status
	}
	return CloseRoomStatus_CLOSE_ROOM_SUCCESS
}

func (x *CloseRoomAck) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// 聊天消息
type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`                                                      // 消息内容
	MessageType   MessageType            `protobuf:"varint,2,opt,name=message_type,json=messageType,proto3,enum=message.MessageType" json:"message_type,omitempty"` // 消息类型
	ReplyTo       uint64                 `protobuf:"varint,3,opt,name=reply_to,json=replyTo,proto3" json:"reply_to,omitempty"`                                      // 回复的消息ID (可选)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_message_message_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{11}
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessage) GetMessageType() MessageType {
	if x != nil {
		return x.MessageType
	}
	return MessageType_MESSAGE_TYPE_TEXT
}

func (x *ChatMessage) GetReplyTo() uint64 {
	if x != nil {
		return x.ReplyTo
	}
	return 0
}

// 聊天消息确认
type ChatMessageAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        uint64                 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`                  // 房间ID (用于确认消息)
	Status        ChatMessageStatus      `protobuf:"varint,2,opt,name=status,proto3,enum=message.ChatMessageStatus" json:"status,omitempty"` // 状态
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`                                 // 失败原因
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessageAck) Reset() {
	*x = ChatMessageAck{}
	mi := &file_message_message_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessageAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessageAck) ProtoMessage() {}

func (x *ChatMessageAck) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessageAck.ProtoReflect.Descriptor instead.
func (*ChatMessageAck) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{12}
}

func (x *ChatMessageAck) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *ChatMessageAck) GetStatus() ChatMessageStatus {
	if x != nil {
		return x.Status
	}
	return ChatMessageStatus_CHAT_MESSAGE_SUCCESS
}

func (x *ChatMessageAck) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// 查询特定消息请求（情况1和3：不确定消息是否收到 + 特定拉取消息）
type MessageFetchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     []byte                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"` // 128位全局消息ID
	Timestamp     uint64                 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                 // 查询时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageFetchRequest) Reset() {
	*x = MessageFetchRequest{}
	mi := &file_message_message_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageFetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageFetchRequest) ProtoMessage() {}

func (x *MessageFetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageFetchRequest.ProtoReflect.Descriptor instead.
func (*MessageFetchRequest) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{13}
}

func (x *MessageFetchRequest) GetMessageId() []byte {
	if x != nil {
		return x.MessageId
	}
	return nil
}

func (x *MessageFetchRequest) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 查询特定消息响应
type MessageFetchResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MessageId      []byte                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`                // 128位全局消息ID
	Exists         bool                   `protobuf:"varint,2,opt,name=exists,proto3" json:"exists,omitempty"`                                      // 消息是否存在
	Status         MessageStatus          `protobuf:"varint,3,opt,name=status,proto3,enum=message.MessageStatus" json:"status,omitempty"`           // 消息状态
	Reason         string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`                                       // 状态原因
	ProcessedAt    uint64                 `protobuf:"varint,5,opt,name=processed_at,json=processedAt,proto3" json:"processed_at,omitempty"`         // 处理时间
	MessageContent *MessageContent        `protobuf:"bytes,6,opt,name=message_content,json=messageContent,proto3" json:"message_content,omitempty"` // 消息内容（如果存在）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MessageFetchResponse) Reset() {
	*x = MessageFetchResponse{}
	mi := &file_message_message_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageFetchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageFetchResponse) ProtoMessage() {}

func (x *MessageFetchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageFetchResponse.ProtoReflect.Descriptor instead.
func (*MessageFetchResponse) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{14}
}

func (x *MessageFetchResponse) GetMessageId() []byte {
	if x != nil {
		return x.MessageId
	}
	return nil
}

func (x *MessageFetchResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *MessageFetchResponse) GetStatus() MessageStatus {
	if x != nil {
		return x.Status
	}
	return MessageStatus_MESSAGE_STATUS_UNKNOWN
}

func (x *MessageFetchResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *MessageFetchResponse) GetProcessedAt() uint64 {
	if x != nil {
		return x.ProcessedAt
	}
	return 0
}

func (x *MessageFetchResponse) GetMessageContent() *MessageContent {
	if x != nil {
		return x.MessageContent
	}
	return nil
}

// 拉取房间消息请求（情况2：加入房间后拉取较近的消息）
type RoomMessageFetchRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RoomId          uint64                 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`                              // 房间ID
	BeforeMessageId uint64                 `protobuf:"varint,2,opt,name=before_message_id,json=beforeMessageId,proto3" json:"before_message_id,omitempty"` // 在此消息ID之前的消息（可选，用于分页）
	Limit           uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                                              // 返回消息数量限制
	SinceTimestamp  uint64                 `protobuf:"varint,4,opt,name=since_timestamp,json=sinceTimestamp,proto3" json:"since_timestamp,omitempty"`      // 从此时间戳开始的消息（可选）
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RoomMessageFetchRequest) Reset() {
	*x = RoomMessageFetchRequest{}
	mi := &file_message_message_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomMessageFetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomMessageFetchRequest) ProtoMessage() {}

func (x *RoomMessageFetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomMessageFetchRequest.ProtoReflect.Descriptor instead.
func (*RoomMessageFetchRequest) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{15}
}

func (x *RoomMessageFetchRequest) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *RoomMessageFetchRequest) GetBeforeMessageId() uint64 {
	if x != nil {
		return x.BeforeMessageId
	}
	return 0
}

func (x *RoomMessageFetchRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *RoomMessageFetchRequest) GetSinceTimestamp() uint64 {
	if x != nil {
		return x.SinceTimestamp
	}
	return 0
}

// 拉取房间消息响应
type RoomMessageFetchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        uint64                 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`                       // 房间ID
	Messages      []*MessageContent      `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`                                  // 消息列表
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`                    // 是否还有更多消息
	NextBeforeId  uint64                 `protobuf:"varint,4,opt,name=next_before_id,json=nextBeforeId,proto3" json:"next_before_id,omitempty"`   // 下一页的before_message_id
	Status        RoomMessageFetchStatus `protobuf:"varint,5,opt,name=status,proto3,enum=message.RoomMessageFetchStatus" json:"status,omitempty"` // 状态
	Reason        string                 `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`                                      // 失败原因
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomMessageFetchResponse) Reset() {
	*x = RoomMessageFetchResponse{}
	mi := &file_message_message_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomMessageFetchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomMessageFetchResponse) ProtoMessage() {}

func (x *RoomMessageFetchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomMessageFetchResponse.ProtoReflect.Descriptor instead.
func (*RoomMessageFetchResponse) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{16}
}

func (x *RoomMessageFetchResponse) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *RoomMessageFetchResponse) GetMessages() []*MessageContent {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *RoomMessageFetchResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *RoomMessageFetchResponse) GetNextBeforeId() uint64 {
	if x != nil {
		return x.NextBeforeId
	}
	return 0
}

func (x *RoomMessageFetchResponse) GetStatus() RoomMessageFetchStatus {
	if x != nil {
		return x.Status
	}
	return RoomMessageFetchStatus_ROOM_MESSAGE_FETCH_SUCCESS
}

func (x *RoomMessageFetchResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// 消息内容
type MessageContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     []byte                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`                                 // 128位全局消息ID
	RoomId        uint64                 `protobuf:"varint,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`                                         // 房间ID
	UserId        uint64                 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                         // 发送者用户ID
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`                                                      // 消息内容
	MessageType   MessageType            `protobuf:"varint,5,opt,name=message_type,json=messageType,proto3,enum=message.MessageType" json:"message_type,omitempty"` // 消息类型
	ReplyTo       uint64                 `protobuf:"varint,6,opt,name=reply_to,json=replyTo,proto3" json:"reply_to,omitempty"`                                      // 回复的消息ID (可选)
	Timestamp     uint64                 `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                                 // 消息时间戳
	Status        MessageStatus          `protobuf:"varint,8,opt,name=status,proto3,enum=message.MessageStatus" json:"status,omitempty"`                            // 消息状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageContent) Reset() {
	*x = MessageContent{}
	mi := &file_message_message_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageContent) ProtoMessage() {}

func (x *MessageContent) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageContent.ProtoReflect.Descriptor instead.
func (*MessageContent) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{17}
}

func (x *MessageContent) GetMessageId() []byte {
	if x != nil {
		return x.MessageId
	}
	return nil
}

func (x *MessageContent) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *MessageContent) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MessageContent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MessageContent) GetMessageType() MessageType {
	if x != nil {
		return x.MessageType
	}
	return MessageType_MESSAGE_TYPE_TEXT
}

func (x *MessageContent) GetReplyTo() uint64 {
	if x != nil {
		return x.ReplyTo
	}
	return 0
}

func (x *MessageContent) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MessageContent) GetStatus() MessageStatus {
	if x != nil {
		return x.Status
	}
	return MessageStatus_MESSAGE_STATUS_UNKNOWN
}

// 心跳
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     uint64                 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // 时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_message_message_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{18}
}

func (x *Heartbeat) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 心跳确认
type HeartbeatAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     uint64                 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                     // 时间戳
	ServerTime    uint64                 `protobuf:"varint,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"` // 服务器时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatAck) Reset() {
	*x = HeartbeatAck{}
	mi := &file_message_message_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatAck) ProtoMessage() {}

func (x *HeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatAck.ProtoReflect.Descriptor instead.
func (*HeartbeatAck) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{19}
}

func (x *HeartbeatAck) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HeartbeatAck) GetServerTime() uint64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

// 房间信息
type RoomInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RoomId         uint64                 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`                         // 房间ID
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                            // 房间名称
	CreatorId      uint64                 `protobuf:"varint,3,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`                // 创建者用户ID
	MaxMembers     uint32                 `protobuf:"varint,4,opt,name=max_members,json=maxMembers,proto3" json:"max_members,omitempty"`             // 最大成员数
	CurrentMembers uint32                 `protobuf:"varint,5,opt,name=current_members,json=currentMembers,proto3" json:"current_members,omitempty"` // 当前成员数
	CreatedAt      uint64                 `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                // 创建时间
	Status         RoomStatus             `protobuf:"varint,7,opt,name=status,proto3,enum=message.RoomStatus" json:"status,omitempty"`               // 房间状态
	MemberIds      []uint64               `protobuf:"varint,8,rep,packed,name=member_ids,json=memberIds,proto3" json:"member_ids,omitempty"`         // 成员用户ID列表
	Password       string                 `protobuf:"bytes,9,opt,name=password,proto3" json:"password,omitempty"`                                    // 房间密码 (可选)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RoomInfo) Reset() {
	*x = RoomInfo{}
	mi := &file_message_message_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomInfo) ProtoMessage() {}

func (x *RoomInfo) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomInfo.ProtoReflect.Descriptor instead.
func (*RoomInfo) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{20}
}

func (x *RoomInfo) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *RoomInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoomInfo) GetCreatorId() uint64 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

func (x *RoomInfo) GetMaxMembers() uint32 {
	if x != nil {
		return x.MaxMembers
	}
	return 0
}

func (x *RoomInfo) GetCurrentMembers() uint32 {
	if x != nil {
		return x.CurrentMembers
	}
	return 0
}

func (x *RoomInfo) GetCreatedAt() uint64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *RoomInfo) GetStatus() RoomStatus {
	if x != nil {
		return x.Status
	}
	return RoomStatus_ROOM_STATUS_OPEN
}

func (x *RoomInfo) GetMemberIds() []uint64 {
	if x != nil {
		return x.MemberIds
	}
	return nil
}

func (x *RoomInfo) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

var File_message_message_proto protoreflect.FileDescriptor

const file_message_message_proto_rawDesc = "" +
	"\n" +
	"\x15message/message.proto\x12\amessage\"\xad\n" +
	"\n" +
	"\x0fMessageEnvelope\x12*\n" +
	"\x11connection_seq_id\x18\x01 \x01(\x04R\x0fconnectionSeqId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\fR\tmessageId\x12C\n" +
	"\x10allocate_room_id\x18\n" +
	" \x01(\v2\x17.message.AllocateRoomIdH\x00R\x0eallocateRoomId\x12M\n" +
	"\x14allocate_room_id_ack\x18\v \x01(\v2\x1a.message.AllocateRoomIdAckH\x00R\x11allocateRoomIdAck\x126\n" +
	"\vcreate_room\x18\f \x01(\v2\x13.message.CreateRoomH\x00R\n" +
	"createRoom\x12@\n" +
	"\x0fcreate_room_ack\x18\r \x01(\v2\x16.message.CreateRoomAckH\x00R\rcreateRoomAck\x120\n" +
	"\tjoin_room\x18\x0e \x01(\v2\x11.message.JoinRoomH\x00R\bjoinRoom\x12:\n" +
	"\rjoin_room_ack\x18\x0f \x01(\v2\x14.message.JoinRoomAckH\x00R\vjoinRoomAck\x123\n" +
	"\n" +
	"leave_room\x18\x10 \x01(\v2\x12.message.LeaveRoomH\x00R\tleaveRoom\x12=\n" +
	"\x0eleave_room_ack\x18\x11 \x01(\v2\x15.message.LeaveRoomAckH\x00R\fleaveRoomAck\x123\n" +
	"\n" +
	"close_room\x18\x12 \x01(\v2\x12.message.CloseRoomH\x00R\tcloseRoom\x12=\n" +
	"\x0eclose_room_ack\x18\x13 \x01(\v2\x15.message.CloseRoomAckH\x00R\fcloseRoomAck\x129\n" +
	"\fchat_message\x18\x14 \x01(\v2\x14.message.ChatMessageH\x00R\vchatMessage\x12C\n" +
	"\x10chat_message_ack\x18\x15 \x01(\v2\x17.message.ChatMessageAckH\x00R\x0echatMessageAck\x12R\n" +
	"\x15message_fetch_request\x18( \x01(\v2\x1c.message.MessageFetchRequestH\x00R\x13messageFetchRequest\x12U\n" +
	"\x16message_fetch_response\x18) \x01(\v2\x1d.message.MessageFetchResponseH\x00R\x14messageFetchResponse\x12_\n" +
	"\x1aroom_message_fetch_request\x18* \x01(\v2 .message.RoomMessageFetchRequestH\x00R\x17roomMessageFetchRequest\x12b\n" +
	"\x1broom_message_fetch_response\x18+ \x01(\v2!.message.RoomMessageFetchResponseH\x00R\x18roomMessageFetchResponse\x122\n" +
	"\theartbeat\x182 \x01(\v2\x12.message.HeartbeatH\x00R\theartbeat\x12<\n" +
	"\rheartbeat_ack\x183 \x01(\v2\x15.message.HeartbeatAckH\x00R\fheartbeatAckB\t\n" +
	"\amessage\"\x10\n" +
	"\x0eAllocateRoomId\"{\n" +
	"\x11AllocateRoomIdAck\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x04R\x06roomId\x125\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1d.message.AllocateRoomIdStatusR\x06status\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"v\n" +
	"\n" +
	"CreateRoom\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x04R\x06roomId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vmax_members\x18\x03 \x01(\rR\n" +
	"maxMembers\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\"\x96\x01\n" +
	"\rCreateRoomAck\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x04R\x06roomId\x121\n" +
	"\x06status\x18\x02 \x01(\x0e2\x19.message.CreateRoomStatusR\x06status\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12!\n" +
	"\frouter_addrs\x18\x04 \x03(\tR\vrouterAddrs\"&\n" +
	"\bJoinRoom\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\"\xc2\x01\n" +
	"\vJoinRoomAck\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x04R\x06roomId\x12/\n" +
	"\x06status\x18\x02 \x01(\x0e2\x17.message.JoinRoomStatusR\x06status\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12.\n" +
	"\troom_info\x18\x04 \x01(\v2\x11.message.RoomInfoR\broomInfo\x12!\n" +
	"\frouter_addrs\x18\x05 \x03(\tR\vrouterAddrs\"\v\n" +
	"\tLeaveRoom\"q\n" +
	"\fLeaveRoomAck\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x04R\x06roomId\x120\n" +
	"\x06status\x18\x02 \x01(\x0e2\x18.message.LeaveRoomStatusR\x06status\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\v\n" +
	"\tCloseRoom\"q\n" +
	"\fCloseRoomAck\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x04R\x06roomId\x120\n" +
	"\x06status\x18\x02 \x01(\x0e2\x18.message.CloseRoomStatusR\x06status\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"{\n" +
	"\vChatMessage\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x127\n" +
	"\fmessage_type\x18\x02 \x01(\x0e2\x14.message.MessageTypeR\vmessageType\x12\x19\n" +
	"\breply_to\x18\x03 \x01(\x04R\areplyTo\"u\n" +
	"\x0eChatMessageAck\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x04R\x06roomId\x122\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1a.message.ChatMessageStatusR\x06status\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"R\n" +
	"\x13MessageFetchRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\fR\tmessageId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x04R\ttimestamp\"\xfa\x01\n" +
	"\x14MessageFetchResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\fR\tmessageId\x12\x16\n" +
	"\x06exists\x18\x02 \x01(\bR\x06exists\x12.\n" +
	"\x06status\x18\x03 \x01(\x0e2\x16.message.MessageStatusR\x06status\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12!\n" +
	"\fprocessed_at\x18\x05 \x01(\x04R\vprocessedAt\x12@\n" +
	"\x0fmessage_content\x18\x06 \x01(\v2\x17.message.MessageContentR\x0emessageContent\"\x9d\x01\n" +
	"\x17RoomMessageFetchRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x04R\x06roomId\x12*\n" +
	"\x11before_message_id\x18\x02 \x01(\x04R\x0fbeforeMessageId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\x12'\n" +
	"\x0fsince_timestamp\x18\x04 \x01(\x04R\x0esinceTimestamp\"\xfa\x01\n" +
	"\x18RoomMessageFetchResponse\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x04R\x06roomId\x123\n" +
	"\bmessages\x18\x02 \x03(\v2\x17.message.MessageContentR\bmessages\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\x12$\n" +
	"\x0enext_before_id\x18\x04 \x01(\x04R\fnextBeforeId\x127\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1f.message.RoomMessageFetchStatusR\x06status\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\"\x9d\x02\n" +
	"\x0eMessageContent\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\fR\tmessageId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\x04R\x06roomId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x04R\x06userId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x127\n" +
	"\fmessage_type\x18\x05 \x01(\x0e2\x14.message.MessageTypeR\vmessageType\x12\x19\n" +
	"\breply_to\x18\x06 \x01(\x04R\areplyTo\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x04R\ttimestamp\x12.\n" +
	"\x06status\x18\b \x01(\x0e2\x16.message.MessageStatusR\x06status\")\n" +
	"\tHeartbeat\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x04R\ttimestamp\"M\n" +
	"\fHeartbeatAck\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x04R\ttimestamp\x12\x1f\n" +
	"\vserver_time\x18\x02 \x01(\x04R\n" +
	"serverTime\"\xa7\x02\n" +
	"\bRoomInfo\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x04R\x06roomId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x03 \x01(\x04R\tcreatorId\x12\x1f\n" +
	"\vmax_members\x18\x04 \x01(\rR\n" +
	"maxMembers\x12'\n" +
	"\x0fcurrent_members\x18\x05 \x01(\rR\x0ecurrentMembers\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x04R\tcreatedAt\x12+\n" +
	"\x06status\x18\a \x01(\x0e2\x13.message.RoomStatusR\x06status\x12\x1d\n" +
	"\n" +
	"member_ids\x18\b \x03(\x04R\tmemberIds\x12\x1a\n" +
	"\bpassword\x18\t \x01(\tR\bpassword*{\n" +
	"\x14AllocateRoomIdStatus\x12\x1c\n" +
	"\x18ALLOCATE_ROOM_ID_SUCCESS\x10\x00\x12\x1b\n" +
	"\x17ALLOCATE_ROOM_ID_FAILED\x10\x01\x12(\n" +
	"$ALLOCATE_ROOM_ID_SERVICE_UNAVAILABLE\x10\x02*\x80\x01\n" +
	"\x10CreateRoomStatus\x12\x17\n" +
	"\x13CREATE_ROOM_SUCCESS\x10\x00\x12\x16\n" +
	"\x12CREATE_ROOM_FAILED\x10\x01\x12\x1b\n" +
	"\x17CREATE_ROOM_ROOM_EXISTS\x10\x02\x12\x1e\n" +
	"\x1aCREATE_ROOM_INVALID_PARAMS\x10\x03*\xb1\x01\n" +
	"\x0eJoinRoomStatus\x12\x15\n" +
	"\x11JOIN_ROOM_SUCCESS\x10\x00\x12\x14\n" +
	"\x10JOIN_ROOM_FAILED\x10\x01\x12\x1c\n" +
	"\x18JOIN_ROOM_ROOM_NOT_FOUND\x10\x02\x12\x17\n" +
	"\x13JOIN_ROOM_ROOM_FULL\x10\x03\x12\x1c\n" +
	"\x18JOIN_ROOM_WRONG_PASSWORD\x10\x04\x12\x1d\n" +
	"\x19JOIN_ROOM_ALREADY_IN_ROOM\x10\x05*\\\n" +
	"\x0fLeaveRoomStatus\x12\x16\n" +
	"\x12LEAVE_ROOM_SUCCESS\x10\x00\x12\x15\n" +
	"\x11LEAVE_ROOM_FAILED\x10\x01\x12\x1a\n" +
	"\x16LEAVE_ROOM_NOT_IN_ROOM\x10\x02*y\n" +
	"\x0fCloseRoomStatus\x12\x16\n" +
	"\x12CLOSE_ROOM_SUCCESS\x10\x00\x12\x15\n" +
	"\x11CLOSE_ROOM_FAILED\x10\x01\x12\x18\n" +
	"\x14CLOSE_ROOM_NOT_OWNER\x10\x02\x12\x1d\n" +
	"\x19CLOSE_ROOM_ROOM_NOT_FOUND\x10\x03*\xcb\x01\n" +
	"\x11ChatMessageStatus\x12\x18\n" +
	"\x14CHAT_MESSAGE_SUCCESS\x10\x00\x12\x17\n" +
	"\x13CHAT_MESSAGE_FAILED\x10\x01\x12!\n" +
	"\x1dCHAT_MESSAGE_USER_NOT_IN_ROOM\x10\x02\x12\x1f\n" +
	"\x1bCHAT_MESSAGE_ROOM_NOT_FOUND\x10\x03\x12\x1c\n" +
	"\x18CHAT_MESSAGE_ROOM_CLOSED\x10\x04\x12!\n" +
	"\x1dCHAT_MESSAGE_CONTENT_TOO_LONG\x10\x05*\x83\x01\n" +
	"\vMessageType\x12\x15\n" +
	"\x11MESSAGE_TYPE_TEXT\x10\x00\x12\x16\n" +
	"\x12MESSAGE_TYPE_IMAGE\x10\x01\x12\x15\n" +
	"\x11MESSAGE_TYPE_FILE\x10\x02\x12\x16\n" +
	"\x12MESSAGE_TYPE_VOICE\x10\x03\x12\x16\n" +
	"\x12MESSAGE_TYPE_VIDEO\x10\x04*\xa4\x01\n" +
	"\x16RoomMessageFetchStatus\x12\x1e\n" +
	"\x1aROOM_MESSAGE_FETCH_SUCCESS\x10\x00\x12\x1d\n" +
	"\x19ROOM_MESSAGE_FETCH_FAILED\x10\x01\x12%\n" +
	"!ROOM_MESSAGE_FETCH_ROOM_NOT_FOUND\x10\x02\x12$\n" +
	" ROOM_MESSAGE_FETCH_ACCESS_DENIED\x10\x03*\xb9\x01\n" +
	"\rMessageStatus\x12\x1a\n" +
	"\x16MESSAGE_STATUS_UNKNOWN\x10\x00\x12\x1a\n" +
	"\x16MESSAGE_STATUS_PENDING\x10\x01\x12\x1d\n" +
	"\x19MESSAGE_STATUS_PROCESSING\x10\x02\x12\x1a\n" +
	"\x16MESSAGE_STATUS_SUCCESS\x10\x03\x12\x19\n" +
	"\x15MESSAGE_STATUS_FAILED\x10\x04\x12\x1a\n" +
	"\x16MESSAGE_STATUS_TIMEOUT\x10\x05*P\n" +
	"\n" +
	"RoomStatus\x12\x14\n" +
	"\x10ROOM_STATUS_OPEN\x10\x00\x12\x16\n" +
	"\x12ROOM_STATUS_CLOSED\x10\x01\x12\x14\n" +
	"\x10ROOM_STATUS_FULL\x10\x02B\x16Z\x14liveChatroom/messageb\x06proto3"

var (
	file_message_message_proto_rawDescOnce sync.Once
	file_message_message_proto_rawDescData []byte
)

func file_message_message_proto_rawDescGZIP() []byte {
	file_message_message_proto_rawDescOnce.Do(func() {
		file_message_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_message_proto_rawDesc), len(file_message_message_proto_rawDesc)))
	})
	return file_message_message_proto_rawDescData
}

var file_message_message_proto_enumTypes = make([]protoimpl.EnumInfo, 10)
var file_message_message_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_message_message_proto_goTypes = []any{
	(AllocateRoomIdStatus)(0),        // 0: message.AllocateRoomIdStatus
	(CreateRoomStatus)(0),            // 1: message.CreateRoomStatus
	(JoinRoomStatus)(0),              // 2: message.JoinRoomStatus
	(LeaveRoomStatus)(0),             // 3: message.LeaveRoomStatus
	(CloseRoomStatus)(0),             // 4: message.CloseRoomStatus
	(ChatMessageStatus)(0),           // 5: message.ChatMessageStatus
	(MessageType)(0),                 // 6: message.MessageType
	(RoomMessageFetchStatus)(0),      // 7: message.RoomMessageFetchStatus
	(MessageStatus)(0),               // 8: message.MessageStatus
	(RoomStatus)(0),                  // 9: message.RoomStatus
	(*MessageEnvelope)(nil),          // 10: message.MessageEnvelope
	(*AllocateRoomId)(nil),           // 11: message.AllocateRoomId
	(*AllocateRoomIdAck)(nil),        // 12: message.AllocateRoomIdAck
	(*CreateRoom)(nil),               // 13: message.CreateRoom
	(*CreateRoomAck)(nil),            // 14: message.CreateRoomAck
	(*JoinRoom)(nil),                 // 15: message.JoinRoom
	(*JoinRoomAck)(nil),              // 16: message.JoinRoomAck
	(*LeaveRoom)(nil),                // 17: message.LeaveRoom
	(*LeaveRoomAck)(nil),             // 18: message.LeaveRoomAck
	(*CloseRoom)(nil),                // 19: message.CloseRoom
	(*CloseRoomAck)(nil),             // 20: message.CloseRoomAck
	(*ChatMessage)(nil),              // 21: message.ChatMessage
	(*ChatMessageAck)(nil),           // 22: message.ChatMessageAck
	(*MessageFetchRequest)(nil),      // 23: message.MessageFetchRequest
	(*MessageFetchResponse)(nil),     // 24: message.MessageFetchResponse
	(*RoomMessageFetchRequest)(nil),  // 25: message.RoomMessageFetchRequest
	(*RoomMessageFetchResponse)(nil), // 26: message.RoomMessageFetchResponse
	(*MessageContent)(nil),           // 27: message.MessageContent
	(*Heartbeat)(nil),                // 28: message.Heartbeat
	(*HeartbeatAck)(nil),             // 29: message.HeartbeatAck
	(*RoomInfo)(nil),                 // 30: message.RoomInfo
}
var file_message_message_proto_depIdxs = []int32{
	11, // 0: message.MessageEnvelope.allocate_room_id:type_name -> message.AllocateRoomId
	12, // 1: message.MessageEnvelope.allocate_room_id_ack:type_name -> message.AllocateRoomIdAck
	13, // 2: message.MessageEnvelope.create_room:type_name -> message.CreateRoom
	14, // 3: message.MessageEnvelope.create_room_ack:type_name -> message.CreateRoomAck
	15, // 4: message.MessageEnvelope.join_room:type_name -> message.JoinRoom
	16, // 5: message.MessageEnvelope.join_room_ack:type_name -> message.JoinRoomAck
	17, // 6: message.MessageEnvelope.leave_room:type_name -> message.LeaveRoom
	18, // 7: message.MessageEnvelope.leave_room_ack:type_name -> message.LeaveRoomAck
	19, // 8: message.MessageEnvelope.close_room:type_name -> message.CloseRoom
	20, // 9: message.MessageEnvelope.close_room_ack:type_name -> message.CloseRoomAck
	21, // 10: message.MessageEnvelope.chat_message:type_name -> message.ChatMessage
	22, // 11: message.MessageEnvelope.chat_message_ack:type_name -> message.ChatMessageAck
	23, // 12: message.MessageEnvelope.message_fetch_request:type_name -> message.MessageFetchRequest
	24, // 13: message.MessageEnvelope.message_fetch_response:type_name -> message.MessageFetchResponse
	25, // 14: message.MessageEnvelope.room_message_fetch_request:type_name -> message.RoomMessageFetchRequest
	26, // 15: message.MessageEnvelope.room_message_fetch_response:type_name -> message.RoomMessageFetchResponse
	28, // 16: message.MessageEnvelope.heartbeat:type_name -> message.Heartbeat
	29, // 17: message.MessageEnvelope.heartbeat_ack:type_name -> message.HeartbeatAck
	0,  // 18: message.AllocateRoomIdAck.status:type_name -> message.AllocateRoomIdStatus
	1,  // 19: message.CreateRoomAck.status:type_name -> message.CreateRoomStatus
	2,  // 20: message.JoinRoomAck.status:type_name -> message.JoinRoomStatus
	30, // 21: message.JoinRoomAck.room_info:type_name -> message.RoomInfo
	3,  // 22: message.LeaveRoomAck.status:type_name -> message.LeaveRoomStatus
	4,  // 23: message.CloseRoomAck.status:type_name -> message.CloseRoomStatus
	6,  // 24: message.ChatMessage.message_type:type_name -> message.MessageType
	5,  // 25: message.ChatMessageAck.status:type_name -> message.ChatMessageStatus
	8,  // 26: message.MessageFetchResponse.status:type_name -> message.MessageStatus
	27, // 27: message.MessageFetchResponse.message_content:type_name -> message.MessageContent
	27, // 28: message.RoomMessageFetchResponse.messages:type_name -> message.MessageContent
	7,  // 29: message.RoomMessageFetchResponse.status:type_name -> message.RoomMessageFetchStatus
	6,  // 30: message.MessageContent.message_type:type_name -> message.MessageType
	8,  // 31: message.MessageContent.status:type_name -> message.MessageStatus
	9,  // 32: message.RoomInfo.status:type_name -> message.RoomStatus
	33, // [33:33] is the sub-list for method output_type
	33, // [33:33] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_message_message_proto_init() }
func file_message_message_proto_init() {
	if File_message_message_proto != nil {
		return
	}
	file_message_message_proto_msgTypes[0].OneofWrappers = []any{
		(*MessageEnvelope_AllocateRoomId)(nil),
		(*MessageEnvelope_AllocateRoomIdAck)(nil),
		(*MessageEnvelope_CreateRoom)(nil),
		(*MessageEnvelope_CreateRoomAck)(nil),
		(*MessageEnvelope_JoinRoom)(nil),
		(*MessageEnvelope_JoinRoomAck)(nil),
		(*MessageEnvelope_LeaveRoom)(nil),
		(*MessageEnvelope_LeaveRoomAck)(nil),
		(*MessageEnvelope_CloseRoom)(nil),
		(*MessageEnvelope_CloseRoomAck)(nil),
		(*MessageEnvelope_ChatMessage)(nil),
		(*MessageEnvelope_ChatMessageAck)(nil),
		(*MessageEnvelope_MessageFetchRequest)(nil),
		(*MessageEnvelope_MessageFetchResponse)(nil),
		(*MessageEnvelope_RoomMessageFetchRequest)(nil),
		(*MessageEnvelope_RoomMessageFetchResponse)(nil),
		(*MessageEnvelope_Heartbeat)(nil),
		(*MessageEnvelope_HeartbeatAck)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_message_proto_rawDesc), len(file_message_message_proto_rawDesc)),
			NumEnums:      10,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_message_proto_goTypes,
		DependencyIndexes: file_message_message_proto_depIdxs,
		EnumInfos:         file_message_message_proto_enumTypes,
		MessageInfos:      file_message_message_proto_msgTypes,
	}.Build()
	File_message_message_proto = out.File
	file_message_message_proto_goTypes = nil
	file_message_message_proto_depIdxs = nil
}
